### ISSUE TITLE
ASE calculator

### ISSUE THREAD

**Issue by vsumaria** [kcl-tscm/mff#5] opened 2019-11-25 23:06 UTC
I have a trained GP potential which I am loading using the calculators function as described in the tutorial. When I try to use the calculator to find energies (even for the given example in the tutorial), I get the following error: 

_asap.AsapError: Invalid unit cell: One or more vectors has zero length.

I am guessing it is to do with the face that the "movie.xyz" atoms have no unit cell. When I had a unit cell, the training was not starting (because one unit cell vector was shorter than the cutoff length). 

Please help me out here. 

Thanks.

**Comment by ClaudioZeni** [comment] 2019-11-26 10:02
Good morning, 

so the issue is two fold:
1) If the movie file has no unit cell, you should add it either to the xyz file itself (i.e. to the header of each of the snaphots), or to the imported ASE atoms object via the command:
`atoms.set_cell([[x1, y1, z1], [x2, y2, z2], [x3, y3, z3]])`
where x, y, z, indicate the components of the cell vectors (if you notice, in the advanced tutorial, this is what is done in "Setup Simulation parameters in ASE").

2) My suggestion is not to train force fields using data where the unit cell has one dimension smaller than the cutoff radius. If that is necessary for some reason, a way around the error would be to duplicate the cell along any cell dimension which is smaller than the cutoff radius.

I hope this helps, I will mark the issue as closed.

All the best, 

Claudio Zeni

**Comment by vsumaria** [comment] 2019-11-26 17:11
So according to the tutorial, I assumed that the training data needs to have a [0 0 0] unit cell. I will give the repeated unit cell a try with my data and update here if it works out.

**Comment by ClaudioZeni** [comment] 2019-11-26 17:48
You can either use a trajectory file where the system is not in periodic boundary conditions (and thus has no unit cell), or a trajectory file where the system is in periodic boundary conditions, and its unit cell has all dimensions larger than the cutoff radius you choose.

**Comment by vsumaria** [comment] 2019-11-26 18:17
So, I trained my data set, making sure that the unit cell has all dimensions larger than the cutoff radius and the training was successful. I was trying to now use this trained model as a ASE calculator to test on new data using the following code: 

m = uf.load_model("data/models/MODEL_ker_TwoBody_ntr_400.json")
mff_calc = calculators.TwoBodySingleSpecies(cutoff, m.grid)
atom.set_calculator(mff_calc)
atom.get_forces()

I am getting the following error: 
energy_local = self.grid_2b(dist, nu=0)
TypeError: 'dict' object is not callable

What am I doing wrong here?

**Comment by ClaudioZeni** [comment] 2019-11-26 18:45
Did you map the GP onto a Mapped force field using the command
`model.build_grid(grid_start, npoints_grid, ncores = ncores)`
before saving it and then loading it?

**Comment by vsumaria** [comment] 2019-11-26 18:50
yes, I did. Here's what my JSON looks like: 

{
    "model": "TwoBodyManySpeciesModel",
    "elements": [
        6,
        8,
        78
    ],
    "r_cut": 2.8,
    "rep_sig": 0.6673366065572663,
    "fitted": [
        "force",
        null
    ],
    "gp": {
        "kernel": "TwoBody",
        "n_train": 400,
        "sigma": 0.4,
        "theta": 0.5599999999999999,
        "noise": 0.001,
        "filename": "GP_ker_TwoBody_ntr_400.npy"
    },
    "grid": {
        "r_min": 1.5,
        "r_num": 100,
        "filename": {
            "0_0": "GRID_0_0_ker_TwoBody_ntr_400.npz",
            "0_1": "GRID_0_1_ker_TwoBody_ntr_400.npz",
            "0_2": "GRID_0_2_ker_TwoBody_ntr_400.npz",
            "1_1": "GRID_1_1_ker_TwoBody_ntr_400.npz",
            "1_2": "GRID_1_2_ker_TwoBody_ntr_400.npz",
            "2_2": "GRID_2_2_ker_TwoBody_ntr_400.npz"
        }
    }

The "GRID" files are in the same folder as the model JSON ("data/models")

**Comment by vsumaria** [comment] 2019-11-26 18:53
Should I be using "TwoBodyManySpecies", I think yes right ? since I have different elements in the training

**Comment by vsumaria** [comment] 2019-11-26 19:31
Ok, that is what was the error. I now am using: 

m = uf.load_model("data/models/MODEL_ker_TwoBody_ntr_400.json")
mff_calc = calculators.TwoBodyManySpecies(cutoff,[6,8,78],m.grid)

And this calculator object works with ASE correctly. 
Thanks @ClaudioZeni for the help.

**Comment by ClaudioZeni** [comment] 2019-11-26 19:34
Perfect, 
next time you have an issue remember to create another one, as different questions should be covered in different issues.
Closing this one.

**Closed as completed by ClaudioZeni** 2019-11-26 19:34 UTC
